- name: Configuring Webserver using Docker
  hosts: all
  gather_facts: no
  tasks:
    - name: Adding Docker repository
      yum_repository:
            name: Docker
            description: Docker Repo
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
            gpgcheck: no
            enabled: 1

    - name: Installing Docker package
      command: "yum install docker-ce -y --nobest"

    - name: Starting docker service 
      service:
            name: "docker"
            state: started
            enabled: yes

    - name: Install python
      package:
            name: python3
            state: present
    - name: Installing Docker SDK for python3
      command: pip3 install docker
    - name: Creating folder and copying html file...
      file:
             path: /webpages
             state: directory
    - name: Copying html files
      copy:
             src: "index.html"
             dest: "/workspace/"
    - name: Creating container using HTTPD Image 
      docker_container:
             name: MyWebServer
             image: httpd
             state: started
             exposed_ports:
                     - "80"
             ports:
                     - "8888:80"
             volumes:
                     - /workspace:/usr/local/apache2/htdocs/
